name: AdventureStopper
version: '${version}'
main: me.will0mane.plugins.adventurestopper.bukkit.AdventureStopperBukkit
authors: [ Will0mane ]
description: Enables command to automatically stop all instances of adventure with right credential
